name: tests

on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['19.3', '20.3']
        elixir: ['1.5', '1.8', '1.9']
        global-mock: [true, false]
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GLOBAL_MOCK: ${{ matrix.global-mock }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
         otp-version: ${{ matrix.otp }}
         elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v1
        with:
         path: deps
         key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
         restore-keys: |
           ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix coveralls.github
